# golangci-lint configuration for local development (version 2.3.0)
# This file is used for local development with golangci-lint v2.x

version: 2

run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true

linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/windevkay/forge
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  funlen:
    lines: 120
    statements: 60
    ignore-comments: true
  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '3'
      - '10'
      - '100'
      - '1000'
  revive:
    rules:
      - name: exported
        arguments: ["checkPrivateReceivers", "sayRepetitiveInsteadOfStutters"]

linters:
  enable:
    # Default enabled linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Additional useful linters
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - mnd
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
    - unconvert
    - unparam
    - whitespace
    - revive

  disable:
    - depguard
    - godox
    - testpackage
    - varnamelen
    - noctx
    - funlen

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - funlen
        - goconst
        - gosec
        - gocyclo
        - dupl
        - lll
        - gocritic
    - path: cmd/.*\.go
      linters:
        - gochecknoinits
    - path: example.*\.go
      linters:
        - mnd
        - gosec
        - gocritic
    - text: "exported.*should have comment.*or be unexported"
      linters:
        - revive
      path: _test\.go
    - text: "don't use `init` function"
      linters:
        - gochecknoinits
      path: cmd/
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
